### ISSUE TITLE
Back route not wokring properly

### ISSUE THREAD

**Issue by radixdt5005** [tezjs/tezjs#101]
# Describe the bug

On radixweb website in success stories pages, on opening any new success story detail page. User has to click twice on the back button to navigate back from success stories detail page to the main landing page. 

URL in the address bar is getting changed but the data on the page is not working.

In the attached video, I have represented the bug in much more detail.

# Expected Behavior

On single click of back button provided by the browser the route should be changed.

# To Reproduce Follow Below Steps

1. Go to https://radixweb.com/success-stories
2. Click on any success story listed there.
3. Use browser back button to navigate back to main detail page.

# Url (stackblitz or plunker or other)

[Attaching video for the same ](https://watch.screencastify.com/v/nI1rAmpiC2Z6ztd2PQTf)

**Comment by ajayojha** [comment]
it seems that there is some problem in the component code, if the framework level route issue then it won't work on-site level instead of any specific page.

Please share the success-story page and respective component code of redirecting route.

**Comment by radixdt5005** [comment]
> component

![image](https://user-images.githubusercontent.com/78441569/193225491-fc740450-fe14-48ea-aa24-e6cdf23cb513.png)

I have use `@click` event on entire `div` and using tezRouter i have passed the value of redirecting route

**Comment by ajayojha** [comment]
You have used `tez-link` for redirecting the route and also you are manually redirecting to the page on the click event of the page, that's the reason it persisting the route history two times. I would suggest please remove the click event from the div element.

I am closing this ticket as no further action is required on this :).
