### ISSUE TITLE
[AMP] : CSS syntax error in tag 'style amp-custom'.

### ISSUE THREAD

**Issue by radixdt5005** [tezjs/tezjs#134]
`@charset "UTF-8";` added to amp-custom style is causing the issue

![image](https://user-images.githubusercontent.com/78441569/206977108-9fdd8d66-e288-4790-93aa-fc7aa6d84f91.png)

More information on : https://search.google.com/test/amp/result?id=qZjthcJxLLXKcbdJEQkPGA

**Comment by ajayojha** [comment]
This you have to manage from the CSS Styling side. Hence, I am closing this ticket as no action required on this.
