### ISSUE TITLE
[AMP] : A mandatory AMP HTML tag is missing from this document.

### ISSUE THREAD

**Issue by radixdt5005** [tezjs/tezjs#135]
![image](https://user-images.githubusercontent.com/78441569/206978267-d9299441-2af2-4afb-b266-0929e537024a.png)

The syntax charset meta tag is considered as wrong as the syntax which is suggested by AMP is `<meta charset="utf-8">`

**Comment by ajayojha** [comment]
closing this ticket as this is fixed in this https://github.com/tezjs/tezjs/issues/137
