### ISSUE TITLE
Infinite redirection after created the new route

### ISSUE THREAD

**Issue by vnkapoor** [tezjs/tezjs#30]
# Describe the bug
Created the new page in the `pages` folder then set the link of that page in the `header` component. When I clicked on the newly created link it redirects me to infinitely

# Expected Behavior
It should work not redirects to infinitely

# To Reproduce
Create the new page
Set the link of that page in header or anywhere
Click on the newly created link

# Url (stackblitz or plunker or other)
For reference URL: https://filebin.net/pidow531q76jm3wk/tezjs-starter-vue-project.webm

**Comment by ajayojha** [comment]
This is a duplicate issue, as the same issue is already [exits](https://github.com/tezjs/tezjs/issues/29), hence I am closing this ticket to track everything in one ticket :).
