### ISSUE TITLE
Logged in user details not maintained in browser session when open the link in new tab 

### ISSUE THREAD

**Issue by vnkapoor** [tezjs/tezjs#32]
# Describe the bug
Set up the Strapi-Vue application, created the admin account and then logged in it redirects me to the dashboard. Now when I click on any of the sidebar link (open it into the new tab) it opens the login page instead of the actual link.

Note: It's working fine when I opened the link on the same page.

# Expected Behavior
It should not ask the user to login again when user open the sidebar link in new tab

# To Reproduce

- Logged in strapi admin dashboard
- Open any of the sidebar link in new tab

# Url (stackblitz or plunker or other)

**Comment by ajayojha** [comment]
@vnkapoor This is not related to tezjs framework, this is related to the [Strapi Framework](https://github.com/strapi/strapi). Please report the issue in the [strapi repo](https://github.com/strapi/strapi).

Hence, I am closing this ticket as no action is required from our end.
