### ISSUE TITLE
Protected API data access issue.

### ISSUE THREAD

**Issue by dbusa429** [tezjs/tezjs#34]
# Describe the bug

Create an Protected API in Strapi Admin.
Unable to access that api data at frontend side.

# Expected Behavior
Need an Guidance through demonstration, How we can set API token at fronend side.

**Comment by ajayojha** [comment]
The feature is available to access the protected APIs with the below configuration :

``js
import {defineTezConfig } from "@tezjs/vite"

export default defineTezConfig({
    strapi: {
        userCredential:{
            identifier: 'user@strapi.io',
            password: 'strapiPassword',
        }
    }
})
```

But there is one catch in this, it's working in strapi 3 with underneath `userCredential` property of `email`. 

I am considering this as a bug and this will be fixed in the next release.
