### ISSUE TITLE
not able to start the project correctly

### ISSUE THREAD

**Issue by Ushmidave** [tezjs/tezjs#5]
# Describe the bug

This framework looks very interesting to explore and learn, tried to create a new project by following the below steps:
1) npm create tez@latest
   project name : demo-app
   select a framework : >> vue
   select a variant : >> tez-vue
2) cd demo-app
3) npm install
4) npm run dev

got below error while running the command :
![image](https://user-images.githubusercontent.com/46391540/185734010-91777851-47b5-46d4-9752-b61f246349ce.png)

Kindly help me with my error ... 

# Expected Behavior

# To Reproduce

# Url (stackblitz or plunker or other)

**Comment by ajayojha** [comment]
@Ushmidave Please update the [nodejs](https://nodejs.org/en/) above the 16.14 version.

**Comment by ajayojha** [comment]
I hope your issue gets resolved, If still you face the issue then please re-open this ticket.

I am closing this ticket as no further action is required.
