### ISSUE TITLE
New added fields are not generating in payload

### ISSUE THREAD

**Issue by radixdt2144** [tezjs/tezjs#53]
If I add new fields from strapi backend in any of the pages and regenarate the payload in frontend then I'm unable to get those newly added fields in payload.

**Comment by ajayojha** [comment]
Please share the enough information as per issue template.

**Comment by radixdt2144** [comment]
### Bug:
New added fields from strapi backend is not generating in payload at frontend side.

### Expected Behavior:
The value of new added field should be generated in payload at frontend side.

### Steps To Reproduce
Note: Page template has been already created
1. Add new field named "displayOrder" after page creation.
2. Check if you are able to get "displayOrder" field in API response as shown in below image.

   ![image](https://user-images.githubusercontent.com/92514919/188373112-0a09bd9c-8866-4146-a3bb-843b0b48ddc2.png)
3. Not getting "displayOrder" field in JSON file generated in payload at frontend side as shown in below image.

    ![image](https://user-images.githubusercontent.com/92514919/188372127-971e1d84-c00f-4f47-a00a-dc9cac907354.png)

**Comment by ajayojha** [comment]
The JSON content won't be updated automatically as soon as update the content in the Strapi.
Here are the two ways to update the JSON file:

- The JSON content will get updated once you refresh the respective content page.
- The second approach is to delete the folder and re-run the project.

If you still facing the issue after following the above-suggested approach then please re-open this ticket with the appropriate use case.

**Comment by radixdt2144** [comment]
I have tried both of the above mentioned approaches to solve the issue, but still facing the same issue.
I had restart the strapi server also and then check, but issue is still there.
We have check this issue in both environment (local and staging of strapi backend).

**Comment by ajayojha** [comment]
At the root level properties won't generate in the JSON, as the framework segregate the data based upon component not on the page level. 
This is not a bug :). If you still need a property at the root then please create a feature request with an appropriate use case. I would be happy to review the use case and implement the same(if fesible).
