### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by R0N1n-dev** [tezjs/tezjs#7]
# Describe the bug
on saving after making changes to file, console error in browser and HMR doesnt work. Page has to be reloaded manually to see changes.

# Expected Behavior
HRM works and page auto updates after saving
![tez-error](https://user-images.githubusercontent.com/83344872/186605888-0ce30910-cf49-4079-92df-e9b7bba9be11.png)

the console as seen from running the dev server.The yellow errors also present from the beginnring before saving any changes
# To Reproduce

# Url (stackblitz or plunker or other)

**Comment by ajayojha** [comment]
@R0N1n-dev  Thanks for reporting this issue, The issue has been fixed in 1.0.0-beta.3 release.

**Comment by R0N1n-dev** [comment]
Okay. It seems to work from me too. but the stuff in yellow persists in the browser console. is it of  any concern?

**Comment by ajayojha** [comment]
Ooops, I missed checking the console warnings … but that won’t create any issue. 

I will check the warnings and fix the same in the next release 😊.

**Comment by ajayojha** [comment]
@R0N1n-dev The browser console warning issue has been fixed in yesterday's release (1.0.0-beta.5).

**Comment by ajayojha** [comment]
Ohhh I missed to check the console warnings … but that won’t create any issue.

I will check the warnings and fix the same in next release 😊.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
