### ISSUE TITLE
There are two meta view-port tags inside head

### ISSUE THREAD

**Issue by saiyed-radix** [tezjs/tezjs#71]
# Describe the bug
There is two meta viewport tag inside `<head>`

# Expected Behavior
There is only one viewport meta tag there if added from Strapi else the default meta viewport tag should be there. 
`<meta name="viewport" content="width=device-width, initial-scale=1">`

# To Reproduce
Currently, there are two meta viewport tags please check the below screenshot.
![image](https://user-images.githubusercontent.com/88128463/189669653-52a75557-9b51-42d1-85b2-5277572335cf.png)

# Url (stackblitz or plunker or other)

**Comment by ajayojha** [comment]
@saiyed-radix The has been fixed in Yesterday's release 1.0.0-beta.5
