### ISSUE TITLE
Getting error when using swagger plugin with Tez-strapi.

### ISSUE THREAD

**Issue by karantekwani** [tezjs/tezjs#85]
# Describe the bug

Tried to use strapi swagger plugin for API documentation. After installing the plugin, facing problem to run the application.

# To Reproduce

Create new Tez-Strapi project and then install swagger plugin for Strapi ( npm install @strapi/plugin-documentation ).

![image](https://user-images.githubusercontent.com/60701729/190153172-60c86a71-f826-4a6d-8f13-77a95172e205.png)

**Comment by ajayojha** [comment]
It seems this is a duplicate [issue](https://github.com/tezjs/tezjs/issues/84), Hence I am closing this ticket to track everything in one ticket.
